[build]
base = "/"
command = "make netlify"
functions = "/functions"
publish = "/public"

[[redirects]]
from = "/*"
status = 200
to = "/.netlify/functions/lambda/:splat"

[[redirects]]
from = "/static/main.css"
status = 200
to = "/.netlify/functions/lambda/static/main.css"

[[redirects]]
from = "/auth/info"
status = 200
to = "/.netlify/functions/lambda/auth/info"

[[redirects]]
from = "/share/"
status = 200
to = "/.netlify/functions/lambda/share"

[build.environment]
GO111MODULE = "on"
GO_VERSION = "1.18"
